<script lang="ts">
	import Table from '$lib/components/table/Table.svelte';
	import TBody from '$lib/components/table/TBody.svelte';
	import Td from '$lib/components/table/Td.svelte';
	import Th from '$lib/components/table/Th.svelte';
	import THead from '$lib/components/table/THead.svelte';
	import Tr from '$lib/components/table/Tr.svelte';
	import type { ParsedComponentProp } from '../../util/parse-component-src';

	export let parsed: Array<ParsedComponentProp>;

	function guessTypeFromValue(value: string | undefined) {
		if (!value) return 'unknown';
		if (value === 'true' || value === 'false') return 'boolean';
		if (value === 'undefined') return 'unknown';
		if (value === 'null') return 'unknown';
		if (value.startsWith('"') && value.endsWith('"')) return 'string';
		if (value.startsWith("'") && value.endsWith("'")) return 'string';
		if (value.startsWith('[') && value.endsWith(']')) return 'Array';
		if (/^[-+]?[0-9]*\.?[0-9]+([eE][-+]?[0-9]+)?$/.test(value)) return 'number';
		if (value.includes('generateRandomId')) return 'string';
		return 'unknown';
	}

	function mapValue(value: string) {
		if (value === "''") return 'Empty string';
		if (value?.includes('generateRandomId')) return 'Autogenerated random ID';
		return value;
	}
</script>

<Table>
	<THead>
		<Tr>
			<Th class="d4r-min-w-[150px]">Name</Th>
			<Th class="d4r-min-w-[300px]">Type</Th>
			<Th class="d4r-min-w-[150px]">Default Value</Th>
		</Tr>
	</THead>
	<TBody>
		{#each parsed as { comment, name, type, defaultValue }}
			<Tr>
				<Td>{name}</Td>
				<Td><code>{type ?? guessTypeFromValue(defaultValue)}</code></Td>
				<Td>{defaultValue ? mapValue(defaultValue) : 'None'}</Td>
			</Tr>
		{/each}
	</TBody>
</Table>
