<script lang="ts">
	import Text from '$lib/components/text/Text.svelte';
	import SvelteMarkdown from 'svelte-markdown';
	import type { ParsedComponentProp } from '../../util/parse-component-src';
	import CodeBlock from '../code-highlight/CodeBlock.svelte';

	export let parsed: Array<ParsedComponentProp>;

	function guessTypeFromValue(value: string | undefined) {
		if (!value) return 'unknown';
		if (value === 'true' || value === 'false') return 'boolean';
		if (value === 'undefined') return 'unknown';
		if (value === 'null') return 'unknown';
		if (value.startsWith('"') && value.endsWith('"')) return 'string';
		if (value.startsWith("'") && value.endsWith("'")) return 'string';
		if (value.startsWith('[') && value.endsWith(']')) return 'Array';
		if (/^[-+]?[0-9]*\.?[0-9]+([eE][-+]?[0-9]+)?$/.test(value)) return 'number';
		if (value.includes('generateRandomId')) return 'string';
		return 'unknown';
	}

	function mapValue(value: string) {
		if (value === "''") return 'Empty string';
		if (value?.includes('generateRandomId')) return 'Autogenerated random ID';
		return value;
	}
</script>

<div class="d4r-space-y-4">
	{#each parsed as { comment, name, type, defaultValue }}
		<div class="d4r-space-y-2 d4r-rounded d4r-bg-white d4r-p-4 dark:d4r-bg-dark-800">
			<Text tag="h4" weight="semibold">{name}</Text>
			<div>
				<Text contrast="low" size="sm" weight="medium">Type</Text>
				<CodeBlock allowWrap language="ts" code={type ?? guessTypeFromValue(defaultValue)} />
			</div>
			<div>
				<Text contrast="low" size="sm" weight="medium">Default Value</Text>
				<CodeBlock allowWrap language="ts" code={defaultValue ? mapValue(defaultValue) : 'None'} />
			</div>
			{#if comment}
				<Text
					tag="div"
					contrast="low"
					class="d4r-prose !d4r-mt-4 d4r-max-w-full dark:d4r-prose-invert"
				>
					<SvelteMarkdown source={comment} />
				</Text>
			{/if}
		</div>
	{/each}
</div>
