<script lang="ts">
	import Table from '$lib/components/table/Table.svelte';
	import TBody from '$lib/components/table/TBody.svelte';
	import Td from '$lib/components/table/Td.svelte';
	import Th from '$lib/components/table/Th.svelte';
	import THead from '$lib/components/table/THead.svelte';
	import Tr from '$lib/components/table/Tr.svelte';
	import Text from '$lib/components/text/Text.svelte';

	export let componentSrc: string;

	let props: [string, string, string][] = [];

	// TODO: Maybe use https://typescript-eslint.io/architecture/typescript-estree/
	//  instead of a complex regex. The current solition kinda works, but it's not
	//  perfect and sometimes has parsing errors.
	const regex = /export let (\S+)(:\s([^=;]+))?(\s=\s([^;]+))?;/gm;

	$: {
		let m;
		while ((m = regex.exec(componentSrc)) !== null) {
			if (m.index === regex.lastIndex) {
				regex.lastIndex++;
			}

			const name = m[1];
			const type = m[3];
			const value = m[5];

			props.push([name, type, value]);
		}
	}

	function guessTypeFromValue(value: string) {
		if (value === 'true' || value === 'false') return 'boolean';
		if (value === 'undefined') return 'unknown';
		if (value === 'null') return 'unknown';
		if (value.startsWith('"') && value.endsWith('"')) return 'string';
		if (value.startsWith("'") && value.endsWith("'")) return 'string';
		if (value.startsWith('[') && value.endsWith(']')) return 'Array';
		return 'unknown';
	}

	function mapValue(value: string) {
		if (value === "''") return 'Empty string';
		if (value?.includes('generateRandomId')) return 'Autogenerated random ID';
		return value;
	}
</script>

<Text contrast="low" size="sm">
	Caution: This table has been automatically generated using a (bad) regular expression. There may
	be instances where the type and default value are incomplete or wrong. This will be fixed in the
	future.
</Text>
<Table>
	<THead>
		<Tr>
			<Th>Name</Th>
			<Th>Type</Th>
			<Th>Default Value</Th>
		</Tr>
	</THead>
	<TBody>
		{#each props as [name, type, value]}
			<Tr>
				<Td>{name}</Td>
				<Td><code>{type ?? guessTypeFromValue(value)}</code></Td>
				<Td>{mapValue(value)}</Td>
			</Tr>
		{/each}
	</TBody>
</Table>
